// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAek7LVIzkfv5uDBi68int2VHWCtucxwGA',
    appId: '1:952006974173:web:506af7d2935fee4b18d934',
    messagingSenderId: '952006974173',
    projectId: 'portfolio-b4066',
    authDomain: 'portfolio-b4066.firebaseapp.com',
    storageBucket: 'portfolio-b4066.firebasestorage.app',
    measurementId: 'G-NWM0VXTSQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqutweSMKW33V0CNkBzMbFFrs7HI2u3to',
    appId: '1:952006974173:android:7796fb83594b1f1718d934',
    messagingSenderId: '952006974173',
    projectId: 'portfolio-b4066',
    storageBucket: 'portfolio-b4066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwfBC_ywNBjOKwTPQ7PsepnuyKEkOhdhc',
    appId: '1:952006974173:ios:77546cccaad0775218d934',
    messagingSenderId: '952006974173',
    projectId: 'portfolio-b4066',
    storageBucket: 'portfolio-b4066.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwfBC_ywNBjOKwTPQ7PsepnuyKEkOhdhc',
    appId: '1:952006974173:ios:77546cccaad0775218d934',
    messagingSenderId: '952006974173',
    projectId: 'portfolio-b4066',
    storageBucket: 'portfolio-b4066.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAek7LVIzkfv5uDBi68int2VHWCtucxwGA',
    appId: '1:952006974173:web:9b1c5d49a8038bb618d934',
    messagingSenderId: '952006974173',
    projectId: 'portfolio-b4066',
    authDomain: 'portfolio-b4066.firebaseapp.com',
    storageBucket: 'portfolio-b4066.firebasestorage.app',
    measurementId: 'G-YFVMFXHNGG',
  );
}
